FORMAT: 1A
HOST: http://127.0.0.1:30000/

# torcontrollerservice

API для управления Tor'ом

# Group Контроллер

## Состояние контроллера [/api/controller]

### Получить состояние контроллера [GET]
+ Response 200 (application/json)
    + Attributes (ControllerInfo)
+ Response 401
  

## Список групп предустановленных настроек [/api/controller/presets]

### Получить список групп предустановленных настроек [GET]
+ Response 200 (application/json)
    + Attributes (array[string])
+ Response 404 (application/json)
    + Attributes (Error)

### Применить группу предустановленных настроек [POST]
+ Attributes (PresetName)

+ Response 200 (application/json)
    + Attributes (ApplyPresetResult)
+ Response 404 (application/json)
    + Attributes (Error)


## Предустановленные настройки [/api/controller/presets/{preset_name}]

### Получить список предустановленных настроек [GET]
+ Response 200 (application/json)
    + Attributes (array[ProcessPresets])

## Список процессов [/api/controller/processes]

### Получить список процессов [GET]
+ Response 200 (application/json)
    + Attributes (array[string])
+ Response 401

# Group Процесс

## Информация о процессе [/api/controller/processes/{process_id}]
+ Parameters
    + process_id (required, string) - идентификатор процесса

### Получить информацию о процессе [GET]
+ Response 200 (application/json)
    + Attributes (ProcessInfo)
+ Response 401
+ Response 404 (application/json)
    + Attributes (Error)


## Управление процессом [/api/controller/processes/{process_id}/action]
+ Parameters
    + process_id (required, string) - идентификатор процесса

### Запуск/остановка [POST]
+ Attributes (ProcessAction)

+ Response 200 (application/json)
    + Attributes (ProcessActionResult)
+ Response 401
+ Response 403 (application/json)
    + Attributes (ProcessActionResult)
+ Response 404 (application/json)
    + Attributes (Error)


## Список конфигураций процесса [/api/controller/processes/{process_id}/configs]
+ Parameters
    + process_id (required, string) - идентификатор процесса

### Получить список конфигураций [GET]
+ Response 200 (application/json)
    + Attributes (array[string])
+ Response 401
+ Response 404 (application/json)
    + Attributes (Error)


## Конфигурация процесса [/api/controller/processes/{process_id}/configs/{config_name}]
+ Parameters
    + process_id (required, string) - идентификатор процесса
    + config_name (required, string) - имя конфигурации

### Получить конфигурацию процесса [GET]
+ Response 200 (application/json)
    + Attributes (ProcessConfiguration)
+ Response 401
+ Response 404 (application/json) 
    + Attributes (Error)


## Опция конфигурации [/api/controller/processes/{process_id}/configs/{config_name}/options/{option_name}]
+ Parameters
    + process_id (required, string) - идентификатор процесса
    + config_name (required, string) - имя конфигурации
    + option_name (required, string) - имя опции

### Получить опцию [GET]
+ Response 200 (application/json)
    + Attributes (Option)
+ Response 401
+ Response 404 (application/json) 
    + Attributes (Error)

### Задать опцию [PUT]
+ Attributes (OptionValue)

+ Response 200 (application/json)
    + Attributes (Option)
+ Response 201 (application/json)
    + Attributes (Option)
+ Response 400
+ Response 401
+ Response 403
+ Response 404 (application/json) 
    + Attributes (Error)

### Удалить опцию [DELETE]
+ Response 204 (application/json)
+ Response 401
+ Response 403
+ Response 404 (application/json) 
    + Attributes (Error)

## Data Structures

# ControllerInfo
Информация о контроллере.
## Properties
+ PID (number, required)

# ProcessInfo
Информация о процессе.
## Properties
+ name (required, string) - название процесса (например, "tor", "privoxy")
+ status (required, enum[string]) - состояние процесса
    + Members
        + `starting`
        + `running`
        + `stopping`
        + `stopped`
+ configs (required, array[string]) - список названий конфигураций

# ProcessConfiguration
Конфигурация процесса. Их может быть несколько - конфиг-файл, параметры командной строки, рантайм-конфгурация.
## Properties
+ name (required, string) - имя конфигурации
+ options (required, array[string]) - список опций

# Option
Описание опции.
## Properties
+ name (required, string)
+ type (required, enum[string])
    + Members
        + `string`
        + `number`
        + `domain`
+ required (required, boolean) - является ли опция необходимой
+ default_value (optional, string) - значение по-умолчанию
+ list (required, boolean) - может ли содержать список значений или одно
+ system (required, boolean) - системные свойства нельзя изменить
+ domain (optional, array[string]) - домен значений для опций доменного типа
+ value (optional, string) - значение опции
+ presentation  (optional, string) - форматированное значение опции

# OptionValue
Значение параметра конфигурации
## Properties
+ value (optional, string) - значение
+ array_value (optional, array[string]) - значение

# ProcessAction
Действие над процессом
## Properties
+ action (required, enum[string]) - состояние процесса
    + Members
        + `start`
        + `stop`

# ProcessActionResult
Результат попытки управления процессом
## Properties
+ status (required, enum[string])
    + Members
        + `OK`
        + `FAIL`

# Error
Описание ошибки.
## Properties
+ message (required, string)
+ category (optional, string)
+ value (optional, number)

# OptionPreset
Предустановленное значение опции option_name.
## Properties
+ option_name (required, string)
+ value (optional, string) - значение
+ array_value (optional, array[string]) - значение

# ConfigPresets
Предустановленные значения параметров секции config_name.
## Properties
+ config_name (required, string)
+ options (required, array[OptionPreset])

# ProcessPresets
Предустановленные значения параметров процесса process_id.
## Properties
+ process_id (required, string)
+ configs (required, array[ConfigPresets])

# PresetName
Имя группы предустановленных настроек.
## Properties
+ name (required, string)

# ApplyPresetResult
Результат попытки применения предустановленных настроек.
## Properties
+ status (required, enum[string])
    + Members
        + `OK`
        + `FAIL`